[default.extend-words]
typ = "typ" # since type is a keyword in Rust
ser = "ser" # Java com.fasterxml.jackson.databind.ser.std.StdSerializer

[files]
extend-exclude = [
    # False positives in randomly-generated strings
    "server/svix-server/migrations/20230505222507_operational_webhook_event-types.up.sql",
    "server/svix-server/migrations/20230505222507_operational_webhook_event-types.down.sql",
]
