[package]
name = "svix-server_derive"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.15"
syn = { version = "2.0.48", features = ["full"] }

[lints]
workspace = true
