name: Server Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Compile server
        run: cargo build --release --manifest-path server/svix-server/Cargo.toml

      - name: Release
        uses: actions/upload-artifact@v4
        with:
          name: svix-server-x86_64-unknown-linux-gnu
          path: server/target/release/svix-server
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}

  docker:
    name: release docker
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Build and tag image
        run: docker build --build-arg GHCR_PAT=${{ secrets.GHCR_PAT }} -t ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/svix-server-updated :${{ github.sha }} .
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PACKAGE_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Publish to GPR
        run: docker push ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/svix-server-updated :${{ github.sha }}
