name: Server Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_push:
    name: release docker
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          
      - name: Build and tag image
        run: docker build --build-arg GHCR_PAT=${{ secrets.GHCR_PAT }} -t ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/svix-server-updated:${{ github.sha }} ./server -f ./server/Dockerfile
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PACKAGE_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Publish to GPR
        run: docker push ${{ secrets.PACKAGE_URL }}/${{ secrets.REGISTRY_USERNAME }}/svix-server-updated:${{ github.sha }}
